### ISSUE TITLE
Please consider to upgrade FlashStore from v0.7 to v0.14

### ISSUE THREAD

**Issue by huan** [botorange/wechaty-puppet-padpro#124] opened 2019-05-12 09:13 UTC
The FlashStore v0.7 is using `nosql-leveldb` which can fix the segfault from `leveldown`.

However, the v0.7 has a dependencies from my test environment `zixia/levelup`. See: 
https://github.com/huan/flash-store/blob/7c776572ba4ce55840012bb292ce2c520fadf519/package.json#L41

Recently, FlashStore upgrade to using the RocksDB from facebook (See https://github.com/huan/flash-store/issues/34), which I hope could solve the segfault problem too.

So I'd like to suggest that we merge #121 to start using the latest version of FlashStore, and then we can monitor if it will be good for us.

**Comment by windmemory** [comment] 2019-05-13 02:10
Sounds great, however, the backend server is unstable recently, let's postpone this change util it get fully fixed.

**Comment by windmemory** [comment] 2019-05-13 05:33
Will upgrade this in `v0.3.x`

**Comment by windmemory** [comment] 2019-05-13 07:02
Merged, please check.

**Comment by huan** [comment] 2019-05-13 10:30
Great. Let's monitor is there's any segmentation fault with v0.3

**Comment by windmemory** [comment] 2019-05-13 12:28
I can not start `wechaty-puppet-padpro` after upgrade to `v0.14`, so rollback the upgrade for now. 

Here is the issue that I created related to this issue:
https://github.com/huan/flash-store/issues/41

Will upgrade to `v0.14` after we get the issue is resolved.

**Comment by huan** [comment] 2019-05-13 12:30
I'd like to suggest you delete all the old db files before you use the new code.

Because I believe the RocksDB and LevelDB might not compatible between binary files.

**Comment by windmemory** [comment] 2019-05-13 12:45
Okay, delete the old db files works for me.

Is there a way to auto detect the file existence and incompatible then auto delete these files? So the upgrade will be much more smoother. Is this technically possible?

Since this is upgrading from old version to new, if this requires manually delete the db files, it requires too much work from the users.

**Comment by huan** [comment] 2019-05-13 13:13
I believe it will have some way to detect, however, I have no idea right now.

Or you should consider keeping using the LevelDB version instead to upgrade to the RocksDB version. If you want to do so, I'll publish a new version of FlashStore with the official LevelDB version for you, for replacing the developing version v0.7.

**Comment by windmemory** [comment] 2019-05-14 02:01
Will you considering adding a parameter or some environment variable for the constructor or something that will control the underlying data store for `flash-store`? Thus if I want to use the new one, I can pass in a parameter, and without any parameters, the `flash-store` will keep using the `levelDB`. And we can tell developers to upgrade to the new version during a period of time, and deprecate the old one some day in the future.

What do you think about this?

**Closed** 2019-06-19 08:26 UTC
