### ISSUE TITLE
接受一个8M的PDF tofilebox，显示timeout

### ISSUE THREAD

**Issue by miewx** [botorange/wechaty-puppet-padpro#33] opened 2018-12-29 07:31 UTC
代码如下，小文件正常
接受一个8M的PDF tofilebox，显示timeout
```
BASE = "/mnt/data/wxfile/"
{Wechaty} = require 'wechaty'
fs = require('fs-extra')
WECHATY_PUPPET_PADPRO_TOKEN = ''
dayjs = require 'dayjs'
puppet = 'wechaty-puppet-padpro'

puppetOptions = {
  token: WECHATY_PUPPET_PADPRO_TOKEN
  name:"bot"
}

bot = new Wechaty({
  puppet,
  puppetOptions,
})



bot.on('scan'
    (qrcode, status) =>
        console.log(
            "Scan QR Code to login: #{status}\nhttps://api.qrserver.com/v1/create-qr-code/?data=#{encodeURIComponent(qrcode)}"
        )
) .on(
    'login'
    (user) =>
        console.log("User #{user} logined")
).on(
    'message'
    (message) =>
        room = message.room()
        if room
            room_name = (await room.topic()).toLowerCase()
            type = message.type()
            if type == bot.Message.Type.Attachment
                user = message.from().name()

                moment = dayjs().format("YYYY-MM-DD · HH-mm-ss")
                save_dir = BASE+room_name+"/"+moment.split("-",1)[0]
                await fs.mkdirp(save_dir)
                file = await message.toFileBox()
                name = file.name.trim()
                name = moment.trim()+" · "+user+" · "+name
                console.log file
                console.log save_dir+name
                await file.toFile(save_dir+"/"+name)
)
.start()

```
log如下
```
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:30 VERB PadproManager Ignore messages without message id. Ignored message type: 【4】
07:20:31 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
TIMEOUT
(node:9404) UnhandledPromiseRejectionWarning: TIMEOUT
(node:9404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:371:25)
    at Socket.emit (events.js:193:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at TCP._handle.close (net.js:610:12)
 code: 'ECONNRESET' }
07:20:31 SILL WechatGateway sendLong() reqSeq: 3637841610
07:20:31 SILL PadproManager syncMessage()
07:20:31 SILL DedupeApi dedupe() no need to dedupe api GrpcSyncMessage.
07:20:31 SILL WechatGateway sendLong() reqSeq: 710890644
07:20:32 SILL WechatGateway sendLong() receive back package size: 17336
07:20:34 SILL WechatGateway sendLong() receive back package size: 17336
```

**Comment by windmemory** [comment] 2019-01-05 02:19
This is caused by cdn request timeout, added retry mechanism to make sure the cdn features won't be affected by random network fluctuation.

Fix is pushed out with `v0.0.34`.

I am going to close this issue, and feel free to reopen this if you see this error again.

**Closed by windmemory** 2019-01-05 02:19 UTC
